/* CryptPad Configuration — Auto-generated by generate-config.sh */

module.exports = {
    httpUnsafeOrigin: 'https://test-docs.rainbow.rocks',
    httpSafeOrigin: 'https://test-docs-sandbox.rainbow.rocks',

    httpAddress: '0.0.0.0',
    httpPort: 3000,
    httpSafePort: 3001,

    /* Storage */
    filePath: './datastore/',
    archivePath: './data/archive',
    pinPath: './data/pins',
    taskPath: './data/tasks',
    blockPath: './block',
    blobPath: './blob',
    blobStagingPath: './data/blobstage',
    decreePath: './data/decrees',

    /* Limits */
    maxUploadSize: 209715200, /* 200MB */

    /* Admin */
    adminKeys: [
        '2ca451d12c11e85853a88ad78b17be18b377a8f988212547'
    ],

    /* Log level */
    logLevel: 'info',

    /* Disable telemetry */
    logFeedback: false,

    /* Allow registration */
    allowRegistration: true,

    /* Archive deleted pads for 90 days */
    archiveRetentionTime: 90,

    /* Remove inactive accounts after 365 days */
    accountRetentionTime: 365,

    /* Branding */
    appTitle: 'Rainbow Docs',
};
