#!/usr/bin/env bash
#
# build-pkg.sh — Build the Rainbow.pkg installer.
#
# Output: installer/build/Rainbow-<version>.pkg
#
# Two outputs from one run:
#   1. A component package (rainbow-component.pkg) — raw payload + scripts
#   2. A product package (Rainbow-<version>.pkg) — wrapped with the
#      installer UI (welcome/conclusion HTML, optional license)
#
# The product package is what users download. For codesigned releases,
# pass DEV_ID="Developer ID Installer: Your Name (TEAMID)" and we'll
# sign + notarize. Without it we produce an unsigned dev .pkg that
# users can right-click → Open to bypass Gatekeeper.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
PAYLOAD_DIR="$BUILD_DIR/payload"
SCRIPTS_DIR="$BUILD_DIR/scripts"

IDENTIFIER="rocks.rainbow.installer"
VERSION="${RAINBOW_VERSION:-$(yq eval '.rainbow.version' "$PROJECT_ROOT/config/rainbow.yaml" 2>/dev/null || echo "0.1.0")}"
COMPONENT_PKG="$BUILD_DIR/rainbow-component.pkg"
PRODUCT_PKG="$BUILD_DIR/Rainbow-$VERSION.pkg"

DEV_ID="${DEV_ID:-}"

# Image the installer pulls on the user's Mac. Defaults to the GHCR
# image for the current release; CI overrides via env to match the
# tag being built. Local dev .pkg builds get the same reference, so
# `make pkg` followed by installing the result will pull whichever
# version of the image is currently published — handy for testing
# the installer flow against a real registry.
RAINBOW_WEB_IMAGE="${RAINBOW_WEB_IMAGE:-ghcr.io/youraerials/rainbow-web:$VERSION}"

# ─── Pre-flight ────────────────────────────────────────────────────
for cmd in pkgbuild productbuild yq; do
    command -v "$cmd" >/dev/null 2>&1 || {
        echo "Missing required command: $cmd" >&2
        exit 1
    }
done

echo "Building Rainbow.pkg v$VERSION"
echo "  Payload root:    $PAYLOAD_DIR"
echo "  Install location: /Applications/Rainbow"
echo

rm -rf "$BUILD_DIR"
mkdir -p "$PAYLOAD_DIR/Applications/Rainbow"
mkdir -p "$SCRIPTS_DIR"

# ─── Payload ───────────────────────────────────────────────────────
# Everything that needs to live on the user's machine after install.
# Build artifacts (dashboard/dist) get rebuilt on-the-fly during install
# anyway, but we ship a pre-built bundle so the wizard works without
# requiring `npm install` post-install.

echo "Preparing payload…"

# Source files for the project
RSYNC_EXCLUDES=(
    --exclude=node_modules
    --exclude=dist
    --exclude=.git
    --exclude=.wrangler
    --exclude="*.tmp"
    --exclude="test"
    --exclude=".DS_Store"
    --exclude="Rainbow-Control-Daemon"  # rebuilt below
    --exclude=".build"                  # Swift / SPM build artifacts
    --exclude="build"                   # installer's own build dir
    --exclude="*.log"
    --exclude=".env"
    --exclude=".env.local"
    # NB: package-lock.json IS needed — the Dockerfile uses `npm ci`
    # which fails without a lock file. Don't add it to excludes.
    # Runtime state in infrastructure/ that gets regenerated by
    # generate-config.sh on each `make setup`. Shipping these would
    # leak whatever was in the dev tree at build time (CF tunnel
    # creds, generated configs pinned to the dev's domain, etc.).
    --exclude="infrastructure/cloudflared/credentials"
    --exclude="*.compiled"
    --exclude="*.compiled.yml"
)
for dir in cli config scripts services cloudflare web app-builder backups docs website infrastructure; do
    if [ -d "$PROJECT_ROOT/$dir" ]; then
        rsync -a "${RSYNC_EXCLUDES[@]}" \
            "$PROJECT_ROOT/$dir/" "$PAYLOAD_DIR/Applications/Rainbow/$dir/"
    fi
done

# postinstall.sh sources helper files at runtime, and the LaunchAgent
# it bootstraps points at /Applications/Rainbow/installer/scripts/
# phase-b-setup.sh — ship just those, not the whole installer/ tree
# (which has build artifacts, the brand site's installer chrome, etc.).
mkdir -p "$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/lib"
mkdir -p "$PAYLOAD_DIR/Applications/Rainbow/installer/resources"
cp "$SCRIPT_DIR/scripts/binaries.lock.sh" \
   "$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/binaries.lock.sh"
cp "$SCRIPT_DIR/scripts/lib/fetch-binary.sh" \
   "$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/lib/fetch-binary.sh"
cp "$SCRIPT_DIR/scripts/lib/fetch-all.sh" \
   "$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/lib/fetch-all.sh"
PHASE_B_PATH="$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/phase-b-setup.sh"
cp "$SCRIPT_DIR/scripts/phase-b-setup.sh" "$PHASE_B_PATH"
# Substitute the GHCR image reference into the copy. The source file
# carries a __RAINBOW_WEB_IMAGE__ placeholder so the working tree
# stays runnable in dev (where the orchestrator builds the image
# locally) — only the .pkg-bound copy gets the registry pin baked in.
sed -i.bak "s|__RAINBOW_WEB_IMAGE__|$RAINBOW_WEB_IMAGE|g" "$PHASE_B_PATH"
rm -f "$PHASE_B_PATH.bak"
chmod +x "$PHASE_B_PATH"
echo "Pinned rainbow-web image to: $RAINBOW_WEB_IMAGE"

# upgrade.sh — the in-app Update banner triggers the control daemon's
# `upgrade` task, which is hardcoded to `installer/scripts/upgrade.sh`.
# Ship it explicitly: the working-tree script in installer/scripts/ is
# excluded by the wholesale rsync above (we deliberately don't ship
# the whole installer/ dir).
cp "$SCRIPT_DIR/scripts/upgrade.sh" \
   "$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/upgrade.sh"
chmod +x "$PAYLOAD_DIR/Applications/Rainbow/installer/scripts/upgrade.sh"
cp "$SCRIPT_DIR/resources/rocks.rainbow.setup.plist" \
   "$PAYLOAD_DIR/Applications/Rainbow/installer/resources/rocks.rainbow.setup.plist"

# Embed the operator's subdomain-manager API secret if the build
# environment provides one. This is the bearer token postinstall will
# use to authenticate against rainbow.rocks's Worker so the wizard can
# claim a subdomain on the user's behalf. The secret is shared across
# all installs (not per-user) — see docs/installer-architecture.md.
# A .pkg without this file still installs cleanly; the wizard just
# returns "not configured" at the provision step.
if [ -n "${RAINBOW_SUBDOMAIN_API_SECRET:-}" ]; then
    SECRET_PATH="$PAYLOAD_DIR/Applications/Rainbow/installer/.subdomain-api-secret"
    printf '%s' "$RAINBOW_SUBDOMAIN_API_SECRET" > "$SECRET_PATH"
    chmod 600 "$SECRET_PATH"
    echo "Embedded subdomain API secret in payload."
else
    echo "RAINBOW_SUBDOMAIN_API_SECRET not set — wizard will say 'not configured' at provision time."
fi

# Compile the host control daemon (Swift) and ship the binary in the
# payload's bin/ directory. Drops the Node dependency for the user's
# Mac — Apple ships the Swift runtime, the compiler is only needed
# here at build time.
echo "Compiling host control daemon (Swift)…"
mkdir -p "$PAYLOAD_DIR/Applications/Rainbow/bin"
swiftc -O "$PROJECT_ROOT/services/control/Daemon.swift" \
    -o "$PAYLOAD_DIR/Applications/Rainbow/bin/Rainbow-Control-Daemon"
chmod +x "$PAYLOAD_DIR/Applications/Rainbow/bin/Rainbow-Control-Daemon"

# Pre-built dashboard/dist — needed for the setup wizard to render
# without an npm step. Rebuild it now if missing.
if [ ! -f "$PROJECT_ROOT/dashboard/dist/index.html" ]; then
    echo "Building dashboard/dist…"
    (cd "$PROJECT_ROOT/dashboard" && npm install --no-audit --no-fund && npm run build) \
        >> "$BUILD_DIR/build.log" 2>&1
fi
mkdir -p "$PAYLOAD_DIR/Applications/Rainbow/dashboard"
rsync -a "$PROJECT_ROOT/dashboard/dist/" "$PAYLOAD_DIR/Applications/Rainbow/dashboard/dist/"
# Ship dashboard's package + tsconfig so the wizard build is reproducible
# from the install dir if the user wants to fork.
for f in package.json tsconfig.json vite.config.ts index.html; do
    cp "$PROJECT_ROOT/dashboard/$f" "$PAYLOAD_DIR/Applications/Rainbow/dashboard/$f"
done
cp -R "$PROJECT_ROOT/dashboard/src" "$PAYLOAD_DIR/Applications/Rainbow/dashboard/src"

# Top-level files
cp "$PROJECT_ROOT/Makefile" "$PAYLOAD_DIR/Applications/Rainbow/"
cp "$PROJECT_ROOT/README.md" "$PAYLOAD_DIR/Applications/Rainbow/"
cp "$PROJECT_ROOT/LICENSE" "$PAYLOAD_DIR/Applications/Rainbow/" 2>/dev/null || true
cp "$PROJECT_ROOT/CLAUDE.md" "$PAYLOAD_DIR/Applications/Rainbow/" 2>/dev/null || true

# Double-click reset shortcut. Lands at /Applications/Rainbow/Reset
# Rainbow.command — Finder runs it in Terminal when the user double-
# clicks. The reset itself goes through scripts/reset-local.sh.
cp "$SCRIPT_DIR/resources/Reset Rainbow.command" \
   "$PAYLOAD_DIR/Applications/Rainbow/Reset Rainbow.command"
chmod +x "$PAYLOAD_DIR/Applications/Rainbow/Reset Rainbow.command"

# Stamp the version. The dashboard's update banner reads this to decide
# whether a newer release is available; the host control daemon also
# returns it from /system/info. upgrade.sh rewrites it on each upgrade.
echo "$VERSION" > "$PAYLOAD_DIR/Applications/Rainbow/.installed-version"

# ─── Scripts ───────────────────────────────────────────────────────
# pkgbuild expects scripts named exactly "preinstall" and "postinstall"
# (no extension). Copy ours under those names.

cp "$SCRIPT_DIR/scripts/preflight.sh" "$SCRIPTS_DIR/preinstall"
cp "$SCRIPT_DIR/scripts/postinstall.sh" "$SCRIPTS_DIR/postinstall"
chmod +x "$SCRIPTS_DIR/preinstall" "$SCRIPTS_DIR/postinstall"

# ─── Build component package ───────────────────────────────────────

echo "Building component package…"
pkgbuild \
    --root "$PAYLOAD_DIR" \
    --scripts "$SCRIPTS_DIR" \
    --identifier "$IDENTIFIER" \
    --version "$VERSION" \
    --install-location "/" \
    "$COMPONENT_PKG"

# ─── Build product package (with installer UI) ─────────────────────

DISTRIBUTION_XML="$BUILD_DIR/distribution.xml"
cat > "$DISTRIBUTION_XML" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="2">
    <title>Rainbow</title>
    <organization>$IDENTIFIER</organization>
    <domains enable_localSystem="true"/>
    <options customize="never" require-scripts="true" rootVolumeOnly="true" hostArchitectures="arm64"/>
    <volume-check>
        <allowed-os-versions>
            <os-version min="26.0"/>
        </allowed-os-versions>
    </volume-check>
    <welcome file="welcome.html" mime-type="text/html"/>
    <conclusion file="conclusion.html" mime-type="text/html"/>
    <pkg-ref id="$IDENTIFIER"/>
    <choices-outline>
        <line choice="default">
            <line choice="$IDENTIFIER"/>
        </line>
    </choices-outline>
    <choice id="default"/>
    <choice id="$IDENTIFIER" visible="false">
        <pkg-ref id="$IDENTIFIER"/>
    </choice>
    <pkg-ref id="$IDENTIFIER" version="$VERSION" onConclusion="none">$(basename "$COMPONENT_PKG")</pkg-ref>
</installer-gui-script>
EOF

echo "Building product package…"
productbuild \
    --distribution "$DISTRIBUTION_XML" \
    --resources "$SCRIPT_DIR/resources" \
    --package-path "$BUILD_DIR" \
    "$PRODUCT_PKG"

# ─── Optional codesigning + notarization ───────────────────────────

if [ -n "$DEV_ID" ]; then
    echo "Signing with: $DEV_ID"
    SIGNED_PKG="$BUILD_DIR/Rainbow-$VERSION-signed.pkg"
    productsign --sign "$DEV_ID" "$PRODUCT_PKG" "$SIGNED_PKG"
    mv "$SIGNED_PKG" "$PRODUCT_PKG"

    if [ -n "${NOTARY_PROFILE:-}" ]; then
        echo "Submitting for notarization (profile: $NOTARY_PROFILE)…"
        xcrun notarytool submit "$PRODUCT_PKG" \
            --keychain-profile "$NOTARY_PROFILE" \
            --wait
        xcrun stapler staple "$PRODUCT_PKG"
    else
        echo "Skipping notarization (set NOTARY_PROFILE to enable)"
    fi
fi

# ─── Done ──────────────────────────────────────────────────────────

echo
echo "Built:"
echo "  $PRODUCT_PKG ($(du -h "$PRODUCT_PKG" | cut -f1))"
[ -n "$DEV_ID" ] && echo "  Signed: yes" || echo "  Signed: no (Gatekeeper will warn — user right-clicks → Open first time)"
echo
echo "To test locally:"
echo "  sudo installer -pkg \"$PRODUCT_PKG\" -target /"
